name: mi_card_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20 # Check for the latest version on pub.dev
  font_awesome_flutter: ^10.1.0  # Ensure this is the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/WhatsApp Image 2024-01-26 at 22.41.07_602840b9.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans
      fonts:
        - asset: fonts/SourceSans3-Bold.ttf
        - asset: fonts/SourceSans3-VariableFont_wght.ttf